<%@page import="eagles.ticket.vo.GameVO"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<%

GameVO gv = (GameVO)request.getAttribute("gv");

String gameCd = (String)request.getAttribute("gameCd");

%>
    
    
    
    
    
    
    
    
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>구역선택</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
<style>
   <%@include file="../headerCSS.jsp" %>
</style>


</head>
<body>

<%@include file="../header.jsp" %>








    <div class="row align-items-md-stretch bg-black">

        <div id="left-view" class="p-5 mb-4 bg-dark col-lg-7 col-md-12">
            <div id="main" class="container-fluid py-5">
                <div class="d-flex justify-content-center align-items-center">



                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="/img/ticket/img_eagles_park.png" usemap="#image-map">

                    <map name="image-map">
                        <area target="_blank" alt="seat1" title="seat1" id="seat1"
                            href="/seatdetail.do?gameCd=<%=gameCd %>"
                            coords="462,658,495,724,540,827,566,844,832,520,871,375,745,368" shape="poly" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Tooltip on top">
                    </map>




                </div>
            </div>
        </div>
        <div id="right-view" class="h-100 p-5 mb-4 bg-black col-lg-5 col-md-12 text-white justify-content-center align-items-center">

            <br><br><br><br><br><br><br>
                <h2 class="text-center">좌석 선택</h2>
                <br> <br><hr><br> <br>
                <div class="row">

                    <div class="col-2"></div>

                    <div class="row col-8">
                        <img class="col" src="/img/teamlogo/한화.png" alt="">
                        <h2 class="col text-center"><br>vs</h2>
                        <img class="col" src="<%=gv.getTeamLogo() %>" alt="">

                    </div>

                    <div class="col-2"></div>

                </div>



                <div class="row">

                    <div class="col-2"></div>

                    <div class="row col-8">
                        <h6 class="col text-center"><br>한화</h6>
                        <h4 class="col text-center"><br></h4>
                        <h6 class="col text-center"><br><%=gv.getTeamName() %></h6>

                    </div>

                    <div class="col-2"></div>

                </div>
                <br>

                <hr>

                <div class="row">

                    <%
                    
                    
                    %>
                        
                        <h3 class="text-center"><br><br><%=gv.getGameDate()%></h3>
                        <h6><br></h6>
                        <h4 class="text-center"><br>한화 생명 이글스 파크</h4>
                    
                </div>




                </div>
                <div id="seatNo"></div>
                <br> <br>

        </div>
    </div>














    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
        </script>
    <script>
     // console.log(document.querySelectorAll('.navbar-nav .nav-link'));
    </script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
        </script>

</body>
</html>